In [2]:
# Food Delivery Data Analysis
### Innomatics Research Labs – Advanced GenAI Internship Entrance Test

#This notebook loads data from CSV, JSON, and SQL files,
#merges them into a final dataset, and performs analysis
#to answer the given questions.

import pandas as pd
import sqlite3

In [3]:
import numpy as np

In [4]:
#Load orders.csv
orders = pd.read_csv("orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [5]:
#Load users.json
users = pd.read_json("users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [7]:
#Load restaurants.sql
conn = sqlite3.connect("restaurants.db")

# Read the SQL file content
with open("restaurants.sql", "r") as f:
    sql_script = f.read()

# Execute the SQL script to create the table and insert data
conn.executescript(sql_script)

restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [8]:
#Merge Orders + Users (LEFT JOIN)
merged_df = orders.merge(users, on="user_id", how="left")
merged_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name,name,city,membership
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular

In [9]:
#Merge with Restaurants Data (LEFT JOIN)
final_df = merged_df.merge(restaurants, on="restaurant_id", how="left")
final_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [10]:
#Save Final Dataset (VERY IMPORTANT)
final_df.to_csv("final_food_delivery_dataset.csv", index=False)

In [12]:
#Total orders by Gold members
final_df[final_df["membership"] == "Gold"].shape[0]

4987

In [13]:
#Revenue by city
final_df.groupby("city")["total_amount"].sum()

city
Bangalore    2206946.58
Chennai      1990513.03
Hyderabad    1889366.58
Pune         1924797.93
Name: total_amount, dtype: float64

In [14]:
#Average order value (Gold)
final_df[final_df["membership"] == "Gold"]["total_amount"].mean()

np.float64(797.1455564467616)

In [15]:
## Conclusion
#- Data from CSV, JSON, and SQL were successfully merged
#- Gold members contribute significantly to revenue
#- City and cuisine-based insights were extracted